### PR TITLE
map

### PR DESCRIPTION
**Pull request by Renaud2002**
beginning of map

### CODE REVIEW

**Review by erivas28 — COMMENTED** [review]
Excited to see this finalized, keep it up Fred :)

**Review by SantiM1 — DISMISSED** [review]
Looks good

**Comment by erivas28** [comment]
Looks great, just need to resolve the merge conflicts

**Comment by Renaud2002** [comment]
thank you, merge conflict solved.

**Review by erivas28 — APPROVED** [review]
Perfect, looks ready to go! :)

**Pull request merged**
