### PR TITLE
Map.2

### PR DESCRIPTION
**Pull request by Renaud2002**
second part of Map implementing geolocation to get user location so when an image is uploaded a maker is put on the map with the location of where the using was.

### CODE REVIEW

**Review by erivas28 — DISMISSED** [review]
Excited to see this live, approved! :)

**Comment by Renaud2002** [comment]
Thank you, same here :)

**Comment by Renaud2002** [comment]
@erivas28 sorry can you approve it again, I have to solve merge conflicts.

**Review by SantiM1 — APPROVED** [review]
Looks good. It's nice that it's basically complety separated from the rest of the program, easier to change in the future and all, with the Marker kind. Good job, let's wrap this up.

**Comment by Renaud2002** [comment]
Thank you

**Pull request merged**
